/**
 * One-time (build-time) font bundler.
 *
 * Downloads Cairo (variable, wght 200–900) and Almarai (300/400/700/800) as
 * woff2 from Google Fonts and rewrites the @font-face CSS to local URLs.
 * Both families are licensed under the SIL Open Font License 1.1 — see
 * THIRD_PARTY_NOTICES.md. The extension itself never touches the network.
 *
 * Output: src/ui/assets/fonts/*.woff2 + src/ui/fonts.css
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = path.join(root, 'src/ui/assets/fonts');

// A modern-Chrome UA makes Google Fonts serve woff2 (variable where available).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const CSS_URLS = [
  'https://fonts.googleapis.com/css2?family=Cairo:wght@200..900&display=swap',
  'https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700;800&display=swap',
];

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

async function fetchBinary(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

await mkdir(fontsDir, { recursive: true });

let combinedCss = `/*
 * Bundled locally — no runtime network requests.
 * Cairo & Almarai © their authors, SIL Open Font License 1.1.
 * Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 */\n\n`;

const seen = new Map(); // remote url -> local filename

for (const cssUrl of CSS_URLS) {
  let css = await fetchText(cssUrl);
  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]);
  for (const remote of urls) {
    if (!seen.has(remote)) {
      const family = /almarai/i.test(remote) ? 'almarai' : 'cairo';
      const base = path.basename(new URL(remote).pathname);
      const name = `${family}-${seen.size}-${base.endsWith('.woff2') ? base : base + '.woff2'}`;
      const local = name.replace(/[^\w.-]/g, '');
      seen.set(remote, local);
      const bin = await fetchBinary(remote);
      await writeFile(path.join(fontsDir, local), bin);
      console.log(`  ${local}  ${(bin.length / 1024).toFixed(1)} KB`);
    }
    css = css.replaceAll(remote, `./assets/fonts/${seen.get(remote)}`);
  }
  combinedCss += css.trim() + '\n\n';
}

await writeFile(path.join(root, 'src/ui/fonts.css'), combinedCss);
console.log(`\nWrote ${seen.size} font files + src/ui/fonts.css`);
